export const Exchanges = [
  {
    id: 'binance',
    name: 'Binance',
    year_established: 2017,
    country: 'Cayman Islands',
    description: 'One of the world’s largest cryptocurrency exchanges by trading volume, offering a wide range of services including spot, futures, and staking options.',
    url: 'https://www.binance.com/',
    image: 'https://coin-images.coingecko.com/markets/images/52/small/binance.jpg?1706864274',
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 1,
    trade_volume_24h_btc: 132325.09436946115,
    trade_volume_24h_btc_normalized: 131039.1832946359,
  },
  {
    id: 'bybit_spot',
    name: 'Bybit',
    year_established: 2018,
    country: 'British Virgin Islands',
    description:
      'Bybit is the world’s second-largest cryptocurrency exchange by trading volume, serving a global community of over 60 million users. Founded in 2018, Bybit is redefining openness in the decentralized world by creating a simpler, open and equal ecosystem for everyone. With a strong focus on Web3, Bybit partners strategically with leading blockchain protocols to provide robust infrastructure and drive on-chain innovation. Renowned for its secure custody, diverse marketplaces, intuitive user experience, and advanced blockchain tools, Bybit bridges the gap between TradFi and DeFi, empowering builders, creators, and enthusiasts to unlock the full potential of Web3. Discover the future of decentralized finance at Bybit.com.',
    url: 'https://www.bybit.com',
    image: 'https://coin-images.coingecko.com/markets/images/698/small/bybit_spot.png?1706864649',
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 2,
    trade_volume_24h_btc: 26391.658850946686,
    trade_volume_24h_btc_normalized: 38282.46426498187,
  },
  {
    id: 'bitget',
    name: 'Bitget',
    year_established: 2018,
    country: 'Seychelles',
    description:
      "Established in 2018, Bitget is the world's leading cryptocurrency exchange and Web3 company. Serving over 100 million users in 150+ countries and regions, the Bitget exchange is committed to helping users trade smarter with its pioneering copy trading feature and other trading solutions, while offering real-time access to Bitcoin price, Ethereum price, and other cryptocurrency prices. Formerly known as BitKeep, Bitget Wallet is a world-class multi-chain crypto wallet that offers an array of comprehensive Web3 solutions and features including wallet functionality, token swap, NFT Marketplace, DApp browser, and more. Bitget is at the forefront of driving crypto adoption through strategic partnerships, such as its role as the Official Crypto Partner of the World's Top Football League, LALIGA, in EASTERN, SEA and LATAM market, as well as a global partner of Turkish National athletes Buse Tosun Çavuşoğlu (Wrestling world champion), Samet Gümüş (Boxing gold medalist) and İlkin Aydın (Volleyball national team), to inspire the global community to embrace the future of cryptocurrency.",
    url: 'https://www.bitget.com/',
    image: 'https://coin-images.coingecko.com/markets/images/540/small/2023-07-25_21.47.43.jpg?1706864507',
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 3,
    trade_volume_24h_btc: 26093.271757101113,
    trade_volume_24h_btc_normalized: 35537.90375033805,
  },
  {
    id: 'okex',
    name: 'OKX',
    year_established: 2017,
    country: 'Seychelles',
    description: 'OKX is a leading global cryptocurrency exchange offering diverse trading options, advanced security, and Web3 integration for millions of users worldwide.\r\n',
    url: 'https://www.okx.com',
    image: 'https://coin-images.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1706864283',
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 4,
    trade_volume_24h_btc: 21695.83610204661,
    trade_volume_24h_btc_normalized: 35621.76702944051,
  },
  {
    id: 'gdax',
    name: 'Coinbase Exchange',
    year_established: 2012,
    country: 'United States',
    description: 'A leading U.S.-based exchange known for its regulatory compliance, user-friendly interface, and support for fiat-to-crypto transactions.',
    url: 'https://www.coinbase.com/',
    image: 'https://coin-images.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1706864258',
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 5,
    trade_volume_24h_btc: 14899.67130475883,
    trade_volume_24h_btc_normalized: 28649.67505548719,
  },
  {
    id: 'kraken',
    name: 'Kraken',
    year_established: 2011,
    country: 'United States',
    description: 'Kraken is a San Francisco-based cryptocurrency exchange, offering a wide range of trading services for various cryptocurrencies and known for its robust security and regulatory compliance efforts.\r\n',
    url: 'https://www.kraken.com/',
    image: 'https://coin-images.coingecko.com/markets/images/29/small/kraken.jpg?1706864265',
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 6,
    trade_volume_24h_btc: 8389.466767709386,
    trade_volume_24h_btc_normalized: 12238.045688466902,
  },
  {
    id: 'mxc',
    name: 'MEXC',
    year_established: 2018,
    country: 'Seychelles',
    description: 'Established in April 2018, MEXC is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.',
    url: 'https://www.mexc.com/',
    image: 'https://coin-images.coingecko.com/markets/images/409/small/logo_new.png?1743600043',
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 7,
    trade_volume_24h_btc: 31520.49360911036,
    trade_volume_24h_btc_normalized: 39672.64143906593,
  },
  {
    id: 'gate',
    name: 'Gate',
    year_established: 2013,
    country: 'Panama',
    description:
      'Established in 2013, Gate is a cryptocurrency exchange platform with over 23 million users across more than 130 countries. It supports spot, futures, margin trading, and wealth management products for over 3,900 cryptocurrencies. As of May 8, 2025, Gate reports a 24-hour spot trading volume that ranks second globally. The platform uses zero-knowledge technology to verify user asset holdings.\r\n\r\nGate’s reported total reserves amount to $10.865 billion, with a reserve ratio of 128.57% and an excess reserve of $2.415 billion. Gate entities have obtained regulatory licenses or approvals in jurisdictions including Lithuania, Argentina, Malta, Italy, Gibraltar, Bahamas, and Hong Kong. In 2024, Gate Group acquired the Japan-licensed exchange Coin Master. Most recently, Gate Technology FZE ("Gate Dubai") received a full operational license from the Virtual Assets Regulatory Authority (VARA) in Dubai.\r\n\r\n',
    url: 'https://www.gate.com',
    image: 'https://coin-images.coingecko.com/markets/images/60/small/Frame_1.png?1747795534',
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 8,
    trade_volume_24h_btc: 27284.87428737904,
    trade_volume_24h_btc_normalized: 32838.566529916476,
  },
  {
    id: 'huobi',
    name: 'HTX',
    year_established: 2013,
    country: 'Seychelles',
    description:
      'HTX (previously Huobi) is a leading cryptocurrency exchange recognized for its strong security measures and a wide range of trading options. With a user-friendly interface and high liquidity, it caters to both novice and experienced traders while offering various incentives like staking and referral programs.',
    url: 'https://www.huobi.com',
    image: 'https://coin-images.coingecko.com/markets/images/25/small/htx.png?1721712842',
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 9,
    trade_volume_24h_btc: 22546.14761702754,
    trade_volume_24h_btc_normalized: 36792.654588973695,
  },
  {
    id: 'crypto_com',
    name: 'Crypto.com Exchange',
    year_established: 2019,
    country: 'Malta',
    description: 'Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards',
    url: 'https://crypto.com/exchange',
    image: 'https://coin-images.coingecko.com/markets/images/589/small/h2oMjPp6_400x400.jpg?1706864542',
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 10,
    trade_volume_24h_btc: 15743.617199704167,
    trade_volume_24h_btc_normalized: 20874.53805151568,
  },
];
